var fauna = [
	{name:"Bunnini", difficulty:"low", zone:, loottable:"A"},
	{name:"Keerop", difficulty:"low", zone:, loottable:"A"},
	{name:"Seerop", difficulty:"low", zone:, loottable:"A"},
	{name:"Zolkanis Hogflier", difficulty:"low", zone:, loottable:"A"},
	{name:"Portabadga", difficulty:"low", zone:, loottable:"A"},
	{name:"Verdant Theermunk", difficulty:"low", zone:, loottable:"C"},
	{name:"Roro", difficulty:"low", zone:, loottable:"B"},
	{name:"Pavu", difficulty:"low", zone:, loottable:"B"},
	{name:"Kinrak", difficulty:"low", zone:"Ilahaesa Mountains", loottable:"D"},
	{name:"Chicheep", difficulty:"low", zone:"Ilahaesa Mountains", loottable:"A"},
	{name:"Lantern Betta", difficulty:"low", zone:, loottable:"E"},
	{name:"Tinder Jeeka", difficulty:"low", zone:, loottable:"A"},
	{name:"Mutant Mandrake", difficulty:"low", zone:"Antikutan", loottable:"C"},
	{name:"Boil Baby", difficulty:"low", zone:"Antikutan", loottable:"A"},
	{name:"Short-horned Leivris", difficulty:"low", zone:, loottable:"C"},
	{name:"Quagha", difficulty:"low", zone:, loottable:"A"},
	{name:"Gorcwehr", difficulty:"low", zone:"Ferokk Ravine", loottable:"D"},
	{name:"Greater Anta", difficulty:"low", zone:"Ferokk Ravine", loottable:"B"},
	{name:"Sand Manta", difficulty:"low", zone:, loottable:"B"},
	{name:"Leptin", difficulty:"low", zone:, loottable:"A"},
	{name:"Anwask", difficulty:"low", zone:, loottable:"B"},
	{name:"Aconix", difficulty:"low", zone:, loottable:"A"},
	{name:"Troldeeren", difficulty:"low", zone:, loottable:"C"},
	{name:"Bauble Griffin", difficulty:"low", zone:, loottable:"A"},
	{name:"Uthornie", difficulty:"low", zone:, loottable:"B"},
	{name:"Vazoi", difficulty:"low", zone:, loottable:"A"},
	{name:"Grub", difficulty:"low", zone:"Gusting Cavern", loottable:"A"},
	{name:"Tullewyrm Moth", difficulty:"low", zone:"Gusting Cavern", loottable:"B"},
	{name:"Tide Buzzard", difficulty:"low", zone:, loottable:"A"},
	{name:"Shirko", difficulty:"low", zone:, loottable:"B"},
	{name:"Softshell Rippleback", difficulty:"low", zone:, loottable:"B"},
	{name:"Plainstalker", difficulty:"low", zone:"Bayan Plateau", loottable:"B"},
	{name:"Feroraptor", difficulty:"low", zone:"Bayan Plateau", loottable:"A"},
	{name:"Cliffshriek", difficulty:"low", zone:, loottable:"B"},
	{name:"Tawny Imp", difficulty:"low", zone:, loottable:"A"},
	{name:"Star-Nosed Yeru", difficulty:"low", zone:, loottable:"A"},
	{name:"Plicilope", difficulty:"low", zone:"Blasting Moors", loottable:"C"},
	{name:"Pinchypollie", difficulty:"low", zone:, loottable:"A"},
	{name:"Giant Pinchiepollie", difficulty:"low", zone:, loottable:"A"},
	{name:"Quald", difficulty:"low", zone:, loottable:"D"},
	{name:"Armatherium", difficulty:"low", zone:"Blasting Moors/Jordskarn", loottable:"D"},
	{name:"Ground Streak", difficulty:"low", zone:"Jordskarn", loottable:"A"},
	{name:"Kanibar Lythersnitch", difficulty:"low", zone:, loottable:"A"},
	{name:"Dellafin", difficulty:"low", zone:, loottable:"B"},
	{name:"Striped Tiag", difficulty:"medium", zone:"Blasting Moors", loottable:"E"},
	{name:"Moorstalker", difficulty:"medium", zone:"Blasting Moors", loottable:"G"},
	{name:"Uise", difficulty:"medium", zone:, loottable:"G"},
	{name:"Atrimott", difficulty:"medium", zone:, loottable:"H"},
	{name:"Qarilope", difficulty:"medium", zone:, loottable:"H"},
	{name:"Naku", difficulty:"medium", zone:, loottable:"G"},
	{name:"Rockboar", difficulty:"medium", zone:, loottable:"G"},
	{name:"Gorgot", difficulty:"medium", zone:, loottable:"H"},
	{name:"Bristled Anta", difficulty:"medium", zone:, loottable:"H"},
	{name:"Scaled Tapir", difficulty:"medium", zone:, loottable:"H"},
	{name:"Feathered Raziq", difficulty:"medium", zone:, loottable:"H"},
	{name:"Grounded Squalm", difficulty:"medium", zone:, loottable:"F"},
	{name:"Vanttor", difficulty:"medium", zone:, loottable:"G"},
	{name:"Spadetail", difficulty:"medium", zone:"Bayan Plateau", loottable:"H"},
	{name:"Red-throated Quilldog", difficulty:"medium", zone:"Bayan Plateau", loottable:"G"},
	{name:"Mad Betta", difficulty:"medium", zone:, loottable:"I"},
	{name:"Cephiathus", difficulty:"medium", zone:, loottable:"H"},
	{name:"Wallow", difficulty:"medium", zone:, loottable:"F"},
	{name:"Burrowbat", difficulty:"medium", zone:"Gusting Cavern", loottable:"J"},
	{name:"Cave Spider", difficulty:"medium", zone:"Gusting Cavern", loottable:"J"},
	{name:"Quillfisher", difficulty:"medium", zone:, loottable:"J"},
	{name:"Dynok", difficulty:"medium", zone:, loottable:"F"},
	{name:"Giant Set", difficulty:"medium", zone:, loottable:"J"},
	{name:"Westsea Luta", difficulty:"medium", zone:, loottable:"J"},
	{name:"Aharabos", difficulty:"medium", zone:, loottable:"F"},
	{name:"Swamp Diceros", difficulty:"medium", zone:, loottable:"H"},
	{name:"Mireghast", difficulty:"medium", zone:, loottable:"G"},
	{name:"Armored Cermi", difficulty:"medium", zone:, loottable:"H"},
	{name:"Raynen", difficulty:"medium", zone:, loottable:"G"},
	{name:"Dwarf Qirnin", difficulty:"medium", zone:"Ferokk Ravine", loottable:"H"},
	{name:"Hoary Warg", difficulty:"medium", zone:"Ferokk Ravine", loottable:"G"},
	{name:"Bald Imp", difficulty:"medium", zone:, loottable:"G"},
	{name:"Moss Coon", difficulty:"medium", zone:, loottable:"G"},
	{name:"Riptide Dalavash", difficulty:"medium", zone:, loottable:"H"},
	{name:"Sea Leivris", difficulty:"medium", zone:, loottable:"H"},
	{name:"Raktaphage", difficulty:"medium", zone:"Antikutan", loottable:"G"},
	{name:"Cleaver", difficulty:"medium", zone:"Antikutan", loottable:"H"},
	{name:"Hogshorne", difficulty:"medium", zone:, loottable:"F"},
	{name:"Quilled Hogflier", difficulty:"medium", zone:, loottable:"G"},
	{name:"Agninek", difficulty:"medium", zone:, loottable:"G"},
	{name:"Ilahaesa Armatherium", difficulty:"medium", zone:"Ilahaesa Mountains", loottable:"F"},
	{name:"Spiny Nesha", difficulty:"medium", zone:"Ilahaesa Mountains", loottable:"G"},
	{name:"Rynack", difficulty:"medium", zone:, loottable:"F"},
	{name:"Nimfie", difficulty:"medium", zone:, loottable:"H"},
	{name:"Tangle Lythersnitch", difficulty:"medium", zone:, loottable:"G"},
	{name:"Orchid Raptor", difficulty:"medium", zone:, loottable:"H"},
	{name:"Davrar", difficulty:"medium", zone:, loottable:"G"},
	{name:"Sandelve", difficulty:"medium", zone:, loottable:"G"},
	{name:"Dusky Imp", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Perasyte", difficulty:"harsh", zone:, loottable:"L"},
	{name:"Banshee Hantu", difficulty:"harsh", zone:, loottable:"M"},
	{name:"Arctic Touskox", difficulty:"harsh", zone:, loottable:"N"},
	{name:"Rasuji", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Undarbir", difficulty:"harsh", zone:"Ilahaesa Mountains", loottable:"K"},
	{name:"Mountain Glider", difficulty:"harsh", zone:"Ilahaesa Mountains", loottable:"L"},
	{name:"Forged Elemental", difficulty:"harsh", zone:, loottable:"L"},
	{name:"Dyness", difficulty:"harsh", zone:, loottable:"M"},
	{name:"Alseer", difficulty:"harsh", zone:"Antikutan", loottable:"M"},
	{name:"Revenant", difficulty:"harsh", zone:"Antikutan", loottable:"M"},
	{name:"Greater Armored Raaksavar", difficulty:"harsh", zone:, loottable:"M"},
	{name:"Snoot", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Salamander Hantu", difficulty:"harsh", zone:, loottable:"M"},
	{name:"Kovombe", difficulty:"harsh", zone:"Ferokk Ravine", loottable:"L"},
	{name:"Howling Wight", difficulty:"harsh", zone:"Ferokk Ravine", loottable:"K"},
	{name:"Combustive Sheerstrike", difficulty:"harsh", zone:"Ferokk Ravine", loottable:"K"},
	{name:"Vipertooth Leviathan", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Caped Wyvern", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Zigzori", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Rayne", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Artscirict", difficulty:"harsh", zone:, loottable:"L"},
	{name:"Ghost Eater", difficulty:"harsh", zone:, loottable:"M"},
	{name:"Ahrial", difficulty:"harsh", zone:, loottable:"M"},
	{name:"Bullchomp", difficulty:"harsh", zone:, loottable:"L"},
	{name:"Royal Qirnin", difficulty:"harsh", zone:, loottable:"N"},
	{name:"Sylphshriek", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Lurg", difficulty:, zone:"harsh", loottable:"K"},
	{name:"Searstalker", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Taskish", difficulty:"harsh", zone:"Gusting Cavern", loottable:"N"},
	{name:"Hyba", difficulty:"harsh", zone:"Gusting Cavern", loottable:"K"},
	{name:"Kaishie", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Solitary Murkhound", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Deepsea Dalavash", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Great Nyki", difficulty:"harsh", zone:"Bayan Plateau", loottable:"N"},
	{name:"Gravidon", difficulty:"harsh", zone:"Bayan Plateau", loottable:"N"},
	{name:"Algae Thrasher", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Jade Kisa", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Thunderhead", difficulty:"harsh", zone:, loottable:"N"},
	{name:"Golden Eshei", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Crater Hog", difficulty:"harsh", zone:, loottable:"N"},
	{name:"Crowned Stalker", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Maned Qirnin", difficulty:"harsh", zone:, loottable:"L"},
	{name:"Shuvi", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Gaurus", difficulty:"harsh", zone:"Blasting Moors", loottable:"N"},
	{name:"Plains Biroru", difficulty:"harsh", zone:"Blasting Moors", loottable:"K"},
	{name:"Plains Lythersnitch", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Solavis", difficulty:"harsh", zone:, loottable:"K"},
	{name:"Flot", difficulty:"harsh", zone:, loottable:"N"}
	]